name: smart_collab
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-47.0.dev <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.16.1
  cloud_functions: ^4.7.2
  easy_localization: ^3.0.5
  file_picker: ^8.0.2
  file_saver: ^0.2.12
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_storage: ^11.7.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.0
  flutter_riverpod: ^2.5.1
  flutter_speed_dial: ^7.0.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.8
  open_file: ^3.3.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.1
  timeago: ^3.6.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  # include assets/images
  assets:
    - assets/images/
    - assets/translations/  
