// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Y6OMs8gOWlvWG1_i5xb0KaNcO5ZJdHM',
    appId: '1:914148944165:ios:5fb0b60ed18a61eca612cc',
    messagingSenderId: '914148944165',
    projectId: 'smart-collab-fd262',
    storageBucket: 'smart-collab-fd262.appspot.com',
    iosClientId: '914148944165-obov15q0kukv3ibd2p0p3k8io8j6ppp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCollab',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHux68tWrPIA7Om1KZK3qfDSXTxtMdqY8',
    appId: '1:914148944165:android:6be81860f69561caa612cc',
    messagingSenderId: '914148944165',
    projectId: 'smart-collab-fd262',
    storageBucket: 'smart-collab-fd262.appspot.com',
  );

}